Server:
  port: 8080 # listening port

Mysql:
  user: "root"
  password: "xxx"
  port: 3306
  db_name: "xxx"

EdgeGPT:
  cookies: '' # how get it please look https://github.com/acheong08/EdgeGPT, input the content of "Export as JSON" in one line
  cookiePath: "cookies.json" # path from main.go,also look https://github.com/acheong08/EdgeGPT please
  proxy: ""